Repository canvas-gamification/canvas-gamification-junit-tests, pull requests merged in 2022-04, with the labels that each got.

#110 Semantic restructure
  src/global/BaseRandomTest.java
  src/global/BaseTest.java
  src/global/tools/Logger.java
  src/global/utils/RandomUtil.java
  src/global/utils/RegexUtil.java
  src/global/variables/clauses/RandomDouble.java
  src/global/variables/clauses/RandomInteger.java
Labels: enhancement, framework

#92 pre_defined_classes-mathematical_program-medium-q10
  src/pre_defined_classes/mathematical_program/medium/q10/Compounding.java
  src/pre_defined_classes/mathematical_program/medium/q10/MainTest.java
Labels: mergeable

#86 pre_defined_classes-mathematical_program-medium-q7
  src/pre_defined_classes/mathematical_program/medium/q7/FastAndWatery.java
  src/pre_defined_classes/mathematical_program/medium/q7/MainTest.java
Labels: prioritize, mergeable

#58 pre defined classes-mathematical program-hard-q4
  src/pre_defined_classes/mathematical_program/hard/q4/CalcBill.java
  src/pre_defined_classes/mathematical_program/hard/q4/MainTest.java
Labels: mergeable

#63 pre-defined classes-mathematical program-hard-q9
  src/pre_defined_classes/mathematical_program/hard/q9/GrowthRate.java
  src/pre_defined_classes/mathematical_program/hard/q9/MainTest.java
Labels: mergeable

#61 pre-defined classes-mathematical program-hard-q7
  src/pre_defined_classes/mathematical_program/hard/q7/MainTest.java
  src/pre_defined_classes/mathematical_program/hard/q7/Water.java
Labels: mergeable

#41 pre_defined_classes-mathematical_programs-hard-q1
  src/pre_defined_classes/mathematical_program/hard/q1/Javademic.java
  src/pre_defined_classes/mathematical_program/hard/q1/MainTest.java
Labels: prioritize

#48 pre_defined_classes-mathematical programs-medium-q4
  src/pre_defined_classes/mathematical_program/medium/q4/BasketballGames.java
  src/pre_defined_classes/mathematical_program/medium/q4/MainTest.java
Labels: prioritize, mergeable

#57 pre defined classes- mathematical programs-hard-q3
  src/pre_defined_classes/mathematical_program/hard/q3/AreaSector.java
  src/pre_defined_classes/mathematical_program/hard/q3/MainTest.java
Labels: prioritize, mergeable

#64 conditionals-simple_programs_with_decision_points-medium-q1
  src/conditionals/simple_programs_with_decision_points/medium/q1/InvestOp.java
  src/conditionals/simple_programs_with_decision_points/medium/q1/MainTest.java
Labels: prioritize, mergeable

#43 pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q1
  src/pre_defined_classes/simple_programs_taking_user_input/hard/q1/MainTest.java
  src/pre_defined_classes/simple_programs_taking_user_input/hard/q1/PayrollTax.java
Labels: mergeable

#114 conditionals-simple_programs_with_decision_points-medium-q8
  src/conditionals/simple_programs_with_decision_points/medium/q8/MainTest.java
  src/conditionals/simple_programs_with_decision_points/medium/q8/TryAngle.java
Labels: mergeable

#118 Multiple placedholder injections
  src/global/BaseTest.java
  src/global/tools/TestSentenceUtil.java
Labels: enhancement, framework

#44 pre_defined_classes-mathematical_program-medium-q1
  src/pre_defined_classes/mathematical_program/medium/q1/BMI.java
  src/pre_defined_classes/mathematical_program/medium/q1/MainTest.java
Labels: mergeable

#47 pre defined classes-mathematical program-medium-q2
  src/pre_defined_classes/mathematical_program/medium/q2/Heron.java
  src/pre_defined_classes/mathematical_program/medium/q2/MainTest.java
Labels: mergeable

#59 pre defined classes-mathematical program-hard-q5
  src/pre_defined_classes/mathematical_program/hard/q5/LeftRight.java
  src/pre_defined_classes/mathematical_program/hard/q5/MainTest.java
Labels: mergeable

#60 pre-defined classes-mathematical program-hard-q6
  src/pre_defined_classes/mathematical_program/hard/q6/MainTest.java
  src/pre_defined_classes/mathematical_program/hard/q6/ShoutOut.java
Labels: mergeable

#76 pre_defined_classes-mathematical_program-medium-q5
  src/pre_defined_classes/mathematical_program/medium/q5/MainTest.java
  src/pre_defined_classes/mathematical_program/medium/q5/TrigVal.java
Labels: mergeable

#79 pre_defined_classes-mathematical_program-medium-q6
  src/pre_defined_classes/mathematical_program/medium/q6/MainTest.java
  src/pre_defined_classes/mathematical_program/medium/q6/SoundsGood.java
Labels: mergeable

#88 pre_defined_classes-mathematical-program-medium-q8
  src/pre_defined_classes/mathematical_program/medium/q8/Earthquake.java
  src/pre_defined_classes/mathematical_program/medium/q8/MainTest.java
Labels: mergeable

#94 conditionals-simple_programs_with_decision_points-medium-q2
  src/conditionals/simple_programs_with_decision_points/medium/q2/MainTest.java
  src/conditionals/simple_programs_with_decision_points/medium/q2/NumberJumble.java
Labels: prioritize, mergeable

#99 Conditionals simple programs with decision points hard q5
  src/conditionals/simple_programs_with_decision_points/hard/q5/CharaComb.java
  src/conditionals/simple_programs_with_decision_points/hard/q5/MainTest.java
Labels: mergeable

#100 conditionals_simple_programs_with_decision_points_hard_q6
  src/conditionals/simple_programs_with_decision_points/hard/q6/MainTest.java
  src/conditionals/simple_programs_with_decision_points/hard/q6/TempCalc.java
Labels: mergeable

#111 conditionals-simple_programs_with_decision_points-medium-q5
  src/conditionals/simple_programs_with_decision_points/medium/q5/LuckyEmp.java
  src/conditionals/simple_programs_with_decision_points/medium/q5/MainTest.java
Labels: prioritize, mergeable

#112 conditionals-simple_programs_with_decision_points-medium-q6
  src/conditionals/simple_programs_with_decision_points/medium/q6/MainTest.java
  src/conditionals/simple_programs_with_decision_points/medium/q6/SquareUp.java
Labels: mergeable

#67 loops_simple_programs_with_repetittion_medium_q1
  src/loops/simple_problems_with_repitition/medium/q1/InTheBin.java
  src/loops/simple_problems_with_repitition/medium/q1/MainTest.java
Labels: mergeable

#55 loops_simple_programs_with_repitition_easy_q8
  src/loops/simple_programs_with_repitition/easy/q8/CaesarSike.java
  src/loops/simple_programs_with_repitition/easy/q8/MainTest.java
Labels: mergeable

#54 loops_simple_programs_with_repitition_easy_q7
  src/loops/simple_programs_with_repitition/easy/q7/AlTeRnAtInGcAsE.java
  src/loops/simple_programs_with_repitition/easy/q7/MainTest.java
Labels: mergeable

#53 loops_simple_programs_with_repitition_easy_q6
  src/loops/simple_programs_with_repitition/easy/q6/CountItUp.java
  src/loops/simple_programs_with_repitition/easy/q6/MainTest.java
Labels: mergeable

#52 loops_simple_programs_with_repitition_easy_q5
  src/loops/simple_programs_with_repitition/easy/q5/MainTest.java
  src/loops/simple_programs_with_repitition/easy/q5/WordCount.java
Labels: mergeable

#51 loops_simple_programs_with_repitition_easy_q4
  src/loops/simple_programs_with_repitition/easy/q4/MainTest.java
  src/loops/simple_programs_with_repitition/easy/q4/ReverseReverse.java
Labels: mergeable

#120 Custom error messages when running with input
  src/global/BaseTest.java
  src/global/tools/TestOption.java
Labels: enhancement, framework

#45 pre defined classes mathematical programs hard Q2
  src/pre_defined_classes/mathematical_program/hard/q2/Javademic.java
  src/pre_defined_classes/mathematical_program/hard/q2/MainTest.java
Labels: prioritize, mergeable

#49 pre defined classes-mathematical program-medium-q3
  src/pre_defined_classes/mathematical_program/medium/q3/MainTest.java
  src/pre_defined_classes/mathematical_program/medium/q3/TrigIdentity.java
Labels: prioritize, mergeable

#68 loops_simple_programs_with_repitition_medium_q2
  src/loops/simple_programs_with_repitition/medium/q2/AlternateIt.java
  src/loops/simple_programs_with_repitition/medium/q2/MainTest.java
Labels: prioritize

#97 Conditionals simple programs with decision points hard q3
  src/conditionals/simple_programs_with_decision_points/hard/q3/MainTest.java
  src/conditionals/simple_programs_with_decision_points/hard/q3/SleepyTime.java
Labels: mergeable

#80 conditional_simple programs with decision points_hard_q1
  src/conditionals/simple_programs_with_decision_points/hard/q1/AbsolutelySure.java
  src/conditionals/simple_programs_with_decision_points/hard/q1/MainTest.java
Labels: mergeable

#90 pre_defined_classes-mathematical_program-medium-q9
  src/pre_defined_classes/mathematical_program/medium/q9/MainTest.java
  src/pre_defined_classes/mathematical_program/medium/q9/TrigIdentity.java
Labels: prioritize, mergeable

#103 conditionals-simple_programs_with_decision_points-medium-q4
  src/conditionals/simple_programs_with_decision_points/medium/q4/MainTest.java
  src/conditionals/simple_programs_with_decision_points/medium/q4/TheBiggerInt.java
Labels: prioritize, mergeable

#113 conditionals-simple_programs_with_decision_points-medium-q7
  src/conditionals/simple_programs_with_decision_points/medium/q7/HProblem.java
  src/conditionals/simple_programs_with_decision_points/medium/q7/MainTest.java
Labels: mergeable

#123 pre_defined_classes-mathematical_program-medium-q5-fixes
  src/pre_defined_classes/mathematical_program/medium/q5/MainTest.java
  src/pre_defined_classes/mathematical_program/medium/q5/TrigVal.java
Labels: prioritize

#102 conditionals_programs_with_decision_points_medium_q1
  src/conditionals/programs_with_decision_points/medium/q1/LetterBox.java
  src/conditionals/programs_with_decision_points/medium/q1/MainTest.java
Labels: mergeable

#39 Methods modular programs hard q1
  src/methods/modular_programming/hard/q1/MainTest.java
  src/methods/modular_programming/hard/q1/RightPrime.java
Labels: mergeable
