Repository canvas-gamification/canvas-gamification-junit-tests, pull requests merged in 2022-07, with the labels that each got.

#243 pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q7
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q7/MainTest.java
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q7/OddOrEven.java
Labels: mergeable

#308 make placeholder nexted group non-capturing
  src/global/BaseRandomTest.java
  src/global/variables/clauses/PlaceHolder.java
Labels: framework

#309 Add optional support for inclusive upper bounds on random char
  src/global/variables/clauses/RandomChar.java
Labels: framework

#310 Add support to assert equals with a built in custom error message for mismatched types
  src/global/tools/CustomAssertions.java
  src/global/tools/TypeMatcher.java
Labels: enhancement, framework

#311 fix double regex
  src/global/variables/clauses/DoubleLiteral.java
Labels: enhancement, framework

#279 conditionals-programs_with_decision_points-hard-q8
  src/conditionals/programs_with_decision_points/hard/q8/MainTest.java
  src/conditionals/programs_with_decision_points/hard/q8/PointsScoring.java
Labels: mergeable

#283 conditionals-programs_with_decision_points-hard-q6
  src/conditionals/programs_with_decision_points/hard/q6/MainTest.java
  src/conditionals/programs_with_decision_points/hard/q6/UniversityLife.java
Labels: mergeable

#235 pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q8
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q8/Attendance.java
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q8/MainTest.java
Labels: mergeable

#245 pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q9
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q9/MainTest.java
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q9/MathPowerUp.java
Labels: mergeable

#253 pre_defined_classes-simple_programs_taking_string_user_input-medium-q7
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q7/MainTest.java
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q7/UrlValidator.java
Labels: mergeable

#265 pre_defined_classes-simple_programs_taking_string_user_input-medium-q9
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q9/MainTest.java
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q9/redditComment.java
Labels: mergeable

#298 loops-simple_programs_with_repetition-hard-q6
  src/loops/simple_programs_with_repitition/hard/q6/MainTest.java
  src/loops/simple_programs_with_repitition/hard/q6/QueryStr.java
Labels: mergeable

#258 conditionals-programs_with_decision_points-medium-q7
  src/conditionals/programs_with_decision_points/medium/q7/JavaTopia.java
  src/conditionals/programs_with_decision_points/medium/q7/MainTest.java
Labels: mergeable

#259 conditionals-programs_with_decision_points-medium-q8
  src/conditionals/programs_with_decision_points/medium/q8/Competition.java
  src/conditionals/programs_with_decision_points/medium/q8/MainTest.java
Labels: mergeable

#280 conditionals-programs_with_decision_points-hard-q9
  src/conditionals/programs_with_decision_points/hard/q9/DrivingFines.java
  src/conditionals/programs_with_decision_points/hard/q9/MainTest.java
Labels: mergeable

#281 conditionals-programs_with_decision_points-hard-q7
  src/conditionals/programs_with_decision_points/hard/q7/MainTest.java
  src/conditionals/programs_with_decision_points/hard/q7/RiskyBusiness.java
Labels: mergeable

#282 conditionals-programs_with_decision_points-hard-q10
  src/conditionals/programs_with_decision_points/hard/q10/DinnerCost.java
  src/conditionals/programs_with_decision_points/hard/q10/MainTest.java
Labels: mergeable

#292 loops-programs_with_repetition-medium-q4
  src/loops/programs_with_repetition/medium/q4/MainTest.java
  src/loops/programs_with_repetition/medium/q4/OurGlass.java
Labels: mergeable

#313 loops-programs_with_repetition-hard-q4
  src/loops/programs_with_repetition/hard/q4/ArtificialSelection.java
  src/loops/programs_with_repetition/hard/q4/MainTest.java
Labels: mergeable

#241 pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q10
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q10/MainTest.java
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q10/PiperSaratoga.java
Labels: mergeable

#242 pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q6
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q6/MainTest.java
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q6/ZipcodeValidator.java
Labels: mergeable

#244 pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q8
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q8/FeelingSophisticated.java
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q8/MainTest.java
Labels: mergeable

#246 pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q10
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q10/MainTest.java
  src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q10/NewSalaryCalculator.java
Labels: mergeable

#252 pre_defined_classes-simple_programs_taking_string_user_input-medium-q6
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q6/HasSpace.java
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q6/MainTest.java
Labels: mergeable

#264 pre_defined_classes-simple_programs_taking_string_user_input-medium-q8
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q8/MainTest.java
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q8/UserName.java
Labels: mergeable

#266 pre_defined_classes-simple_programs_taking_string_user_input-medium-q10
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q10/MainTeset.java
  src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q10/Palindrome.java
Labels: mergeable

#267 pre_defined_classes-simple_programs_taking_string_user_input-hard-q6
  src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q6/CanValidator.java
  src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q6/MainTest.java
Labels: mergeable

#70 loops-simple_programs_with_repetition-medium-q4
  src/loops/simple_programs_with_repetition/medium/q4/MainTest.java
  src/loops/simple_programs_with_repetition/medium/q4/SerieslyQuestionMark.java
Labels: prioritize

#71 loops-simple_programs_with_repetition-medium-q5
  src/loops/simple_programs_with_repetition/medium/q5/PerfektKyoob.java
  src/loops/simple_programs_with_repetition/medium/q5/PerfektKyoobTest.java
Labels: prioritize

#72 loops-simple_programs_with_repetition-medium-q6
  src/loops/simple_programs_with_repitition/medium/q6/MainTest.java
  src/loops/simple_programs_with_repitition/medium/q6/SumthingSerious.java
Labels: prioritize

#73 loops-simple_programs_with_repetition-medium-q7
  src/loops/simple_programs_with_repetition/medium/q7/MainTest.java
  src/loops/simple_programs_with_repetition/medium/q7/SeriesSeries.java
Labels: prioritize

#74 loops-simple_programs_with_repetition-hard-q9
  src/loops/simple_programs_with_repetition/hard/q9/MainTest.java
  src/loops/simple_programs_with_repetition/hard/q9/OutTheBin.java
Labels: prioritize
