Repository canvas-gamification/canvas-gamification-junit-tests, pull requests merged in 2022-03, with the labels that each got.

#56 Fix print vs println bug
  src/global/utils/RegexUtil.java
Labels: bug

#78 Add more specific message for double literal
  src/global/variables/clauses/DoubleLiteral.java
  src/temp/QuestionExample.java
Labels: framework

#83 Input based testing
  src/global/BaseRandomTest.java
  src/global/BaseTest.java
  src/global/exceptions/InvalidClauseException.java
  src/global/exceptions/InvalidTestOptionException.java
  src/global/tools/TestOption.java
  src/global/tools/TestSentenceUtil.java
  src/global/utils/RegexUtil.java
  src/global/variables/Clause.java
  src/global/variables/RandomClause.java
  src/global/variables/clauses/DoubleLiteral.java
  src/global/variables/clauses/IntegerLiteral.java
  src/global/variables/clauses/PlaceHolder.java
  src/global/variables/clauses/RandomChar.java
  src/global/variables/clauses/RandomDouble.java
  src/global/variables/clauses/RandomInteger.java
  src/temp/ClauseExample.java
  src/temp/Example.java
Labels: enhancement, framework

#105 Fix negative integer issue
  .gitignore
  src/global/utils/RegexUtil.java
  src/global/variables/clauses/IntegerLiteral.java
Labels: bug, framework

#106 Input testing and Injections
  src/global/BaseRandomTest.java
  src/global/BaseTest.java
  src/global/exceptions/InvalidClauseException.java
  src/global/exceptions/InvalidTestOptionException.java
  src/global/tools/TestOption.java
  src/global/tools/TestSentenceUtil.java
  src/global/utils/RegexUtil.java
  src/global/variables/Clause.java
  src/global/variables/RandomClause.java
  src/global/variables/clauses/DoubleLiteral.java
  src/global/variables/clauses/IntegerLiteral.java
  src/global/variables/clauses/PlaceHolder.java
  src/global/variables/clauses/RandomChar.java
  src/global/variables/clauses/RandomDouble.java
  src/global/variables/clauses/RandomInteger.java
  src/temp/ClauseExample.java
  src/temp/Example.java
Labels: enhancement, framework
